### ISSUE TITLE
Replace "send and email to" with "email" in `/.github/ISSUE_TEMPLATE/BRAINSTORM.md` [line 10]

### ISSUE THREAD

**Issue by alexanderholman** [alexanderholman-archive/enki#2]
# Attention
**If you are reporting a security vulnerability, do NOT open an issue. Instead, please send an email to [security@holman.email](mailto:security@holman.email). Thank you.**

**Sub-task of #1**

## Description
Consider using email. 
Incorrect:  
He was going to send an email to her. 
Correct:  
He was going to email her. 
Powered by LanguageTool

**To do list**
- [ ] Replace "send and email to" with "email" in `/.github/ISSUE_TEMPLATE/BRAINSTORM.md` [line 10](https://github.com/alexanderholman/enki/blob/57a34153452bd03bf2448ed2e18e8b419a07f4dd/.github/ISSUE_TEMPLATE/BRAINSTORM.md?plain=1#L10)

## Additional Details
**Additional information or requirements**
No additional information or requirements

## Checklist
Please check that you have completed the following steps:
- [x] Assigned the issue, if you know to whom it should be assigned.
- [x] Correctly labelled the issue to the best of your knowledge.
- [x] Checked that the issue isn't a duplicate or another, or what another similar issue doesn't already exist. If another issue exists that is closed, please re-open that ticket.
